export const FETCH_BLOG_DETAIL_REQUEST = 'FETCH_BLOG_DETAIL_REQUEST'
export const FETCH_BLOG_DETAIL_SUCCESS = 'FETCH_BLOG_DETAIL_SUCCESS'
export const FETCH_BLOG_DETAIL_FAIL = 'FETCH_BLOG_DETAIL_FAIL'
